# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
  accumulate_grad_batches: 5
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.BinConv
    init_args:
      context_length: 96
      num_bins: 500
      min_bin_value: -10
      max_bin_value: 10
      is_prob_forecast: true
      scaler_type: null # or null
      kernel_size_across_bins_2d: 3 # prev: 3
      kernel_size_across_bins_1d: 3 # prev: 11 #what about 7,7?
      num_filters_2d: 96
      num_filters_1d: 96
      kernel_size_ffn: 21
      num_1d_layers: 2
      num_blocks: 3
      dropout: 0.35
      is_cum_sum: false
  learning_rate: 0.0001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: etth2
      split_val: true
      scaler: temporal+binary # identity, standard, temporal
      context_length: 96
      prediction_length: 96
      num_bins: 500
      min_bin_value: -10
      max_bin_value: 10
  batch_size: 6
  test_batch_size: 32
  num_workers: 8