# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 50
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
  accumulate_grad_batches: 4
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.BinConv
    init_args:
      context_length: 36
      num_bins: 1000
      is_prob_forecast: true
      scaler_type: null # or null
      kernel_size_across_bins_2d: 3 # prev: 3
      kernel_size_across_bins_1d: 3 # prev: 11 #what about 7,7?
      num_filters_2d: 36
      num_filters_1d: 36
      kernel_size_ffn: 51
      num_1d_layers: 2
      num_blocks: 3
      dropout: 0.35
      is_cum_sum: false
  learning_rate: 0.0001
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: illness_ltsf
      path: /home/covpreduser/Blob/v-jiawezhang/data/all_datasets/
      split_val: true
      scaler: normalization+binary # identity, standard, temporal
      context_length: 36
      prediction_length: 36
  batch_size: 8
  test_batch_size: 8
  num_workers: 8